print("Welcome to the simple calculator")
print("This calculator adds two numbers supplied by the user")
Num1 = int(input("Type first number here "))
Num2 = int(input("Type second number here "))
print("Your answer is",(((Num1) / (Num2))))
